### ISSUE TITLE
Better tables

### ISSUE THREAD

**Issue by markseu** [markseu/yellowcms#38]
It's possible to make tables with [Markdown](http://www.tablesgenerator.com/markdown_tables), but in reality it is very limited without some CSS to make it look nice. I like to add a few CSS classes, maybe [Bootstrap](http://getbootstrap.com/css/#tables) like, for tables with/without borders.

**Comment by markseu** [comment]
I don't think it's possible with Markdown. Classes for tables didn't get implemented in michelf/php-markdown#157

**Comment by dajare** [comment]
But it's just CSS, isn't it? Have a look at [this quick demo](http://www.sudalyph.org/yellow/blog/testing-tables). I've pulled the CSS from [Skel Baseline](http://getskel.com/downloads/skel-baseline/), and altered the "alt" from `table.alt {}` to `.altTb table {}`, etc., and wrapped the "altTb" table in a div:

```
<div markdown="1" style="width: 50%" class="altTb">

| Function name | Description                    |
| ------------- | ------------------------------ |
| `help()`      | Display the help window.       |
| `destroy()`   | **Destroy your computer!**     |
| `please()`    | *don't know what this is for*  |

</div>
```
So there's a "default" table (no `class` wrapper) and an "alt" table (using a DIV wrapper with the `markdown="1"` switch set).

Does that get you where you want to go?

**Comment by markseu** [comment]
You are right, wrapping table in a div is another alternative.

**Comment by markseu** [comment]
I updated existing themes, so tables look more Bootstrap/Baseline like (horizontal stripes). Didn't add multiple classes, so out-of-the-box there is one table style per theme.
