### ISSUE TITLE
Contact page with mandatory input fields

### ISSUE THREAD

**Issue by pnagl** [markseu/yellowcms#42]
Hello

I would like to templates / contact use.
Unfortunately, the input is not checked (mandatory).

How do I customize the template so required fields are checked?

Thx
Peter

**Comment by markseu** [comment]
I'm afraid currently there is no support to make input mandatory. But it's something that can be added in the future. Thanks for your feedback.

**Comment by varakh** [comment]
Edit the contact.php and replace the sendMail thing with this one. It does not show any specific error, but 
- all fields are mandatory now
- german umlauts are parsed correctly.

https://paste.xinu.at/2QGPPuk/php

**Comment by markseu** [comment]
There's a new contact template with help from @varakh. It will check if the email message is empty, for details see [source code](https://github.com/markseu/yellowcms-extensions/blob/47a3032a0097d2a9b4d83336cc5502a79943642e/templates/contact/contact.php#L46). You can customize it and check all input fields, if you like. Hope you like it.

**Comment by markseu** [comment]
Should be working now. Thanks for testing @pnagl.

**Comment by hysonlee** [comment]
hi @markseu and @pnagl , thanks for your working. I have tried the [contact template](https://github.com/markseu/yellowcms-extensions/tree/master/templates/contact), but there was an error show as **Fatal error: Can't use function return value in write context in contact.php on line 46**. 

If add a line before the L46 as   
`$_REQUEST["message"]=trim($_REQUEST["message"]);`    
also modify the L46(so it should be L47 then) as   
`if(empty($_REQUEST["message"])) $status = "incomplete";` that will be working fine.

**Comment by markseu** [comment]
Thank you for your feedback. Looks like I missed this, it doesn't happen in newer PHP. Which PHP version do you use?

**Comment by markseu** [comment]
Should be fixed now.

**Comment by hysonlee** [comment]
Yes, that's all right.I tested on web hosting with PHP version 5.4.35.
