### ISSUE TITLE
Adding Class to Image and Remove In-line Style

### ISSUE THREAD

**Issue by indadam** [markseu/yellowcms#43]
Hello-

Is there a way to add a class to an image inserted into the content? E.g.:

    ![image img-responsive](image-file.jpg)

Also, I would like the width and height styles removed from the generated code, so turn this:

    <img src="/media/images/image-file.jpg" width="720" height="846" alt="image" title="image">

Into this:

    <img src="/media/images/image-file.jpg" alt="image" title="image" class="img-responsive">

Is this possible? Thank you.

**Comment by indadam** [comment]
Nevermind, I've been reading Daring Fireball's docs on Markdown, I'll just use `<img>` tags. Thank you!

**Comment by markseu** [comment]
Hi Adam, you can also use the [image plugin](https://github.com/markseu/yellowcms-extensions/tree/master/plugins/image) to add a class. Hope this helps!

**Comment by indadam** [comment]
Actually, one more question, is there a way to remove the `<p>` tags from around the images?

I'm wanting to use the Twitter Bootstrap framework for template, and it tends to have issues with image inside of `<p>` tags.

**Comment by markseu** [comment]
I think the Markdown parser likes to wrap images inside an element, like `<p>` or `<li>`, depending on the context. If you're doing something more elaborate, it's maybe easier to write it in HTML.

**Comment by indadam** [comment]
Yeah, that's what I was thinking too, but it seems to be wrapping `<img>` tags as well. It doesn't wrap `<div>` tags, so I went Googling, and it seems like you have to programmatically use PHP to remove the `<p>` tags, which seems a bit extreme.

On the bright side, it seems that Bootstrap also no longer cares if `<img>` tags are wrapped in `<p>` tags, so I guess I'll just deal with it. :-) Thanks!

**Comment by markseu** [comment]
You're welcome, thanks for your feedback! :)

**Comment by hysonlee** [comment]
hi @indadam , I think you can try to edit the theme CSS file and add line like `.content p img {  }` ,it may avoid (at least reduce) the influence of `<img>` wrapping on `<p>`.
