### ISSUE TITLE
Date and time format configuration

### ISSUE THREAD

**Issue by wunderfeyd** [markseu/yellowcms#46]
It would be nice to allow different output date/time formats, either by current user language or by a global setting. This would:

* improve the end user experience with YellowCMS
* reduce the (coding) work to be done by the website owner
* create a better flow in reading content created by the CMS

What do you think?

**Comment by markseu** [comment]
Good question, should the date format be in the [language settings](https://github.com/markseu/yellowcms/blob/master/system/config/language-en.ini) or [global settings](https://github.com/markseu/yellowcms/blob/master/system/config/config.ini)?

**Comment by wunderfeyd** [comment]
I prefer the language settings. In this case a multilanguage blog/website would deliver the most suitable format automatically. No thinking required, except the basic/standard configuration of YellowCMS which has to be done anyway.

**Comment by markseu** [comment]
Thanks, that makes a lot of sense. I added it to the language settings. Please have a look if it's working.

**Comment by wunderfeyd** [comment]
Thank you very much. Seems to work perfectly. Nice work.
