### ISSUE TITLE
Wrong media links when editing

### ISSUE THREAD

**Issue by varakh** [markseu/yellowcms#48]
The urls to media data is wrongly interpretated, if in the edit/admin view.

Example:
I have Yellow in a subfolder called /post/.

Edit URL: /post/admin/my-blog-entry-slug
Images on this view are: /admin/post/media/images/test.png
Code in my-blog-entry-slug.txt: ![image](test.png)

Correct should be: /media/images/test.png

**Comment by markseu** [comment]
Looks like a problem in the Markdown plugin, it doesn't happen in the image plugin.

**Comment by markseu** [comment]
Should be fixed now. Thanks for testing and reporting bugs! :smile:

**Comment by varakh** [comment]
Still getting the missing images error.

**Comment by markseu** [comment]
I tested `![image](icon.png)`. Can you produce an error on the [demo server](http://demo.datenstrom.se/)?

**Comment by varakh** [comment]
Maybe this is happening because I have it as 1-home? Cannot reproduce the error on the demo server. :( But you can see the error occuring in my pictures (mail).

**Comment by markseu** [comment]
Which Yellow version do you have?

**Comment by varakh** [comment]
I updated to the latest one by merging all your changes.

**Comment by markseu** [comment]
No, it should work with any configuration settings and in any folder. It works for me.

**Comment by varakh** [comment]
Yes. It should now. We spoke via mail. So I will close it now. Good job fixing this.
