### ISSUE TITLE
Musiclist snippet: List of music (ogg/mp3)

### ISSUE THREAD

**Issue by nibreh** [markseu/yellowcms#50]
Hello

Like the snippet imagelist, I suggest a snippet who list music (ogg/mp3) from a _music_ directory in /media and play them in a _audio_ tag.

I use this scripts for my personal music band :
https://github.com/tomnatt/html5-audio-script
https://github.com/jaredblyth/php-html5-audio-jukebox

What do you think ?

**Comment by markseu** [comment]
Yes, that's a really good idea.

**Comment by markseu** [comment]
I've send you an email with a snippet. Let me know if you wanted something different.

**Comment by nibreh** [comment]
Thanks ! Here it is : https://github.com/nibreh/yellowcms-musiclist

**Comment by markseu** [comment]
Happy to help :)
