### ISSUE TITLE
Blog filter and published month name

### ISSUE THREAD

**Issue by pnagl** [markseu/yellowcms#52]
![blogarticles_php](https://cloud.githubusercontent.com/assets/8503195/5899167/f55d4dea-a557-11e4-83d7-1ebc138fb80d.png)

Thus, the name of the month (blagarchives) is correctly displayed in blogarticles.php I changed a few lines.

 Example: http://sandbox.nagl.ch/blog/published:2014-12/

 greeting
 Peter

**Comment by markseu** [comment]
Thanks Peter, really good feedback. 

If I understand your right, you are looking for a blog archive with month names, e.g. `January 2015`. I think this can be solved together with  [Blog and month names](https://github.com/markseu/yellowcms/issues/51). It's a common problem, when we solve it there it should work in the blog archive as well.

**Comment by pnagl** [comment]
Works well so far.

 In the archive you could change the display of the filter yet.

 http://sandbox.nagl.ch/blog/published:2013-05/
 Blog: 2013-05

 would be nice

 Blog: 05.2013

 Thank You
 Peter

**Comment by markseu** [comment]
This is next on my TODO list.

**Comment by pnagl** [comment]
Perfectly!

Thank You
Peter

**Comment by markseu** [comment]
Should be working now. Blog template and snippet use the same function for formatting a date.

**Comment by pnagl** [comment]
Perfectly!

http://yellow.nagl.ch

Thank You
Peter

**Comment by markseu** [comment]
Thanks for testing
