### ISSUE TITLE
NGINX

### ISSUE THREAD

**Issue by varakh** [markseu/yellowcms#58]
Hi,

I recently switched to nginx and the nginx doc config is not working. It has problems with media folder. I don't know why. :( Help appreciated!

```
nginx[19490]: 2015/02/28 21:26:22 [crit] 19499#0: *2 stat() "/srv/http/domain/htdocs/media/themes/flatsite.css" failed (13: Permission denied)
nginx[19490]: 2015/02/28 21:26:22 [crit] 19499#0: *1 stat() "/srv/http/domain/htdocs/media/plugins/fontawesome.css" failed (13: Permission denied)
nginx[19490]: 2015/02/28 21:26:22 [crit] 19499#0: *3 stat() "/srv/http/domain/htdocs/media/images/test.png" failed (13: Permission denied)
```

**Comment by markseu** [comment]
Afraid I am not a big help with Nginx. Have a look at your file permissions, can media files be read by all users? Perhaps someone else knows more.

**Comment by varakh** [comment]
file permissions are set correctly. everything works except for files in media and btw not all, just theme things and images.

i am using arch as my server os, so updating isnt possible. it's the latest version :P
